version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    networks:
      - app-network

  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - '8080:8080'
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: 'unless-stopped'
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge